name: Deploy on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9'

      - name: Start Local Devnet
        run: |
          docker run -d --name ethereum-node         -p 8545:8545 -p 30303:30303     vatman/client-go --dev --http --http.api eth,web3,net --http.corsdomain "http://remix.ethereum.org"

      - name: Deploy Hardhat Project
        working-directory: ./hardhat
        run: |
          npm install --save-dev hardhat
          npx hardhat run scripts/deploy.js --network localhost

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Upload Docker Image
        run: |
          docker tag ethereum-node  vatman/client-go-hardhat:latest
          docker push vatman/client-go-hardhat:latest
